services:
  - type: web
    name: travel-api
    env: node
    rootDir: api
    buildCommand: npm ci
    startCommand: node index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 10000
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_TO
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:5173

  - type: static
    name: travel-client
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://travel-api.onrender.com/api/*
